### PR TITLE
Serializable Ribbon 3-class Framework and init process

### PR DESCRIPTION
**Pull request by robobenklein**
Core relation between the main view and the individual ribbons was established

### CODE REVIEW

**Comment by robobenklein** [comment]
Now has savestate for pre-CR state, save fallback, bad serialize recovery, and proper activate / deactivate hooks!

**Comment by robobenklein** [comment]
gifrecord_2019-02-16_011645

**Comment by tkeyes25** [comment]
Having a tough time running the package when I check out. Know the fix?

screen shot 2019-02-18 at 12 08 46 am

**Comment by tkeyes25** [comment]
Also, lot of code I do not understand, so looks good! Hahaha, maybe we can go over it Wednesday. I tried to read through the changes but was difficult

**Comment by robobenklein** [comment]
Well if neither you nor @AZHenley can understand what's going on then I guess I need more comments.

Anything in specific @tkeyes25 ?

**Comment by tkeyes25** [comment]
Nothing too specific, mainly more on me for being new to this. But I can still try to review if need be

**Comment by robobenklein** [comment]
Well if you were able to download and run it then I'd consider that good enough for dev

**Pull request merged**
