### PR TITLE
Hide tabs

### PR DESCRIPTION
**Pull request by tkeyes25**
Code for #4. Will need to address this again when dealing with serializing data (if the user shuts down, we will probably want to save the state of the tabs)

### CODE REVIEW

**Comment by robobenklein** [comment]
Turns out recent Atom versions apparently have an option:

image

I have this disabled and it hides the tabs when I only have one open in the workspace, but probably isn't going to do what we want.

Instead, I'd suggest we store the previous state of the tabs package in our serialization of the package, and disable it in activate() and restore from state in deactivate.

This is so that if I already disabled tabs and toggled CodeRibbon I won't get them switched

**Comment by robobenklein** [comment]
In #16 with the init/deinit process, we can have a serializable state flag at the plugin level for the previous state of the tabs plugin and use that to restore user preference.

**Comment by tkeyes25** [comment]
I think I understand what to do here. Will research and work on this tomorrow

**Comment by tkeyes25** [comment]
Forgo this? I'll let you close / comment @robobenklein

**Comment by robobenklein** [comment]
Gonna keep tabs but change some things instead...

**Pull request closed without merging**
