### PR TITLE
Tracking: Release merge

### PR DESCRIPTION
**Pull request by robobenklein**
Tracking for release of an alpha version.

### CODE REVIEW

**Comment by robobenklein** [comment]
@tkeyes25 can you do a bug check on this?

**Comment by tkeyes25** [comment]
Saw your change and looks good

**Comment by tkeyes25** [comment]
I really wish we could get #29 before merging

**Comment by tkeyes25** [comment]
I actually found a bug with horizontal scrolling, will make issue

**Comment by tkeyes25** [comment]
@robobenklein Let's go ahead and merge before Monday (I believe that is what AZH said). Sadly that empty patch thing is just not being friendly, up to preference on how to handle it for a master merge. I'm thinking just going back to text would be sufficient to the user (i.e. "Empty patch")

**Pull request merged**
